#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "icinga"
name = "Icinga"
description.en = "Infrastructure monitoring system"
description.fr = "Système de surveillance des infrastructures"

version = "2.16.5~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-or-later"
website = "https://icinga.com/"

admindoc = "https://icinga.com/docs/"

code = "https://github.com/Icinga/icinga2"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = true
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/icinga"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/Icinga/icinga2/archive/refs/tags/v2.16.5.tar.gz"
        sha256 = "e94f4711e9d6c062d356080a85636714c0dc7d2ac9b49471e02487446ff8d1e1"
        prefetch = false

        autoupdate.strategy = "latest_github_release"

        [resources.sources.linuxfabrik]
        url = "https://github.com/Linuxfabrik/monitoring-plugins/archive/refs/tags/v7.0.0.tar.gz"
        sha256 = "7dd98afb13a43d85fb9a5fd531420b487e8eaf2bc8557a8f4904f0a57f905bed"
        prefetch = false

        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5665

    [resources.apt]
    packages = [
        "mariadb-server"
    ]

    packages_from_raw_bash = """
    if [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
        echo "php8.2, php8.2-cli, php8.2-common, php8.2-curl, php8.2-fpm, php8.2-gd, php8.2-intl, php8.2-ldap, php8.2-mbstring, php8.2-mysql, php8.2-opcache, php8.2-pgsql, php8.2-readline, php8.2-soap, php8.2-xml, php8.2-imagick";
    elif [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
        echo "php8.4, php8.4-cli, php8.4-common, php8.4-curl, php8.4-fpm, php8.4-gd, php8.4-intl, php8.4-ldap, php8.4-mbstring, php8.4-mysql, php8.4-opcache, php8.4-pgsql, php8.4-readline, php8.4-soap, php8.4-xml, php8.4-imagick";
    fi
    """

    [resources.apt.extras.icinga]
    repo = "deb https://packages.icinga.com/debian icinga-__YNH_DEBIAN_VERSION__ main"
    key = "https://packages.icinga.com/icinga.key"
    packages = [
        "icinga2",
        "icingacli",
        "icingadb",
        "icingadb-redis",
        "icingadb-web",
        "icingaweb2",
        "icinga-director",
        "monitoring-plugins",
        "icinga2-ido-mysql"
    ]

    [resources.apt.extras.linuxfabrik]
    repo = "deb https://repo.linuxfabrik.ch/monitoring-plugins/debian/ __YNH_DEBIAN_VERSION__-release main"
    key = "https://repo.linuxfabrik.ch/linuxfabrik.key"
    packages = [
        "linuxfabrik-monitoring-plugins"
    ]

    [resources.database]
    type = "mysql"
