/**
 * The ApiUser objects are used for authentication against the API.
 */
object ApiUser "root" {
  password = "__API_ROOT_PWD__"
  // client_cn = ""

  permissions = [ "*" ]
}
object ApiUser "icingadb-web" {
    password = "__API_PWD__"
    permissions = [ "actions/*", "objects/modify/*", "objects/query/*", "status/query" ]
}