/**
 * The db_ido_mysql library implements IDO functionality
 * for MySQL.
 */

library "db_ido_mysql"

object IdoMysqlConnection "ido-mysql" {
  user = "__DB_USER__",
  password = "__DB_PWD__",
  host = "localhost",
  database = "__DB_NAME__ido"
}

