#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

mkdir -p "$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.yml" --destination="/etc/icingadb/config.yml"

chmod 640 "/etc/icingadb/config.yml"
chown "icingadb:root" "/etc/icingadb/config.yml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

yunohost service add "icinga2" --description="icinga2"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing $app..."

rm -rf /etc/icingaweb2
ln -s $install_dir /etc/icingaweb2

icinga2 api setup
ynh_systemctl --service="icinga2" --action="restart"
ynh_mysql_db_shell <<< "CREATE DATABASE ${db_name}director DEFAULT CHARACTER SET 'utf8';"
ynh_mysql_db_shell <<< "USE ${db_name}director;"
ynh_mysql_db_shell <<< "GRANT ALL PRIVILEGES ON ${db_name}director.* TO '${db_user}'@'localhost' WITH GRANT OPTION;"
ynh_mysql_db_shell <<< "FLUSH PRIVILEGES;"
ynh_mysql_db_shell <<< "CREATE DATABASE ${db_name}web2 DEFAULT CHARACTER SET 'utf8';"
ynh_mysql_db_shell <<< "USE ${db_name}web2;"
ynh_mysql_db_shell <<< "GRANT ALL PRIVILEGES ON ${db_name}web2.* TO '${db_user}'@'localhost' WITH GRANT OPTION;"
ynh_mysql_db_shell <<< "FLUSH PRIVILEGES;"
ynh_mysql_db_shell < /usr/share/icingadb/schema/mysql/schema.sql

systemctl enable --now icingadb-redis
icinga2 feature enable icingadb
systemctl enable --now icingadb
ynh_systemctl --service="icingadb-redis" --action="restart"
ynh_systemctl --service="icingadb" --action="restart"
ynh_systemctl --service="icinga2" --action="restart"

addgroup --system icingaweb2;
usermod -a -G icingaweb2 www-data;
icingacli setup config directory --group icingaweb2 --config="$install_dir";
icingacli setup token create --config="$install_dir";
token=$(icingacli setup token show --config="$install_dir";)

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="icinga2" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed. $token ${db_name}web2 $db_user $db_pwd"
