#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

api_pwd=$(ynh_string_random --length=8)
ynh_app_setting_set --key=api_pwd --value=$api_pwd

api_root_pwd=$(ynh_string_random --length=8)
ynh_app_setting_set --key=api_root_pwd --value=$api_root_pwd

host_name=$(hostname)

testing=false

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

mkdir -p "$install_dir"
mkdir -p "$install_dir/enabledModules"
mkdir -p "$install_dir/modules/director/"
mkdir -p "$install_dir/modules/icingadb/"
mkdir -p "$install_dir/modules/monitoring/"

ynh_safe_rm "/etc/icingaweb2"
ln -s $install_dir /etc/icingaweb2
ln -s /usr/share/icingaweb2/modules/icingadb $install_dir/enabledModules/icingadb
ln -s /usr/share/icingaweb2/modules/director $install_dir/enabledModules/director
ln -s /usr/share/icingaweb2/modules/incubator $install_dir/enabledModules/incubator
ln -s /usr/share/icingaweb2/modules/doc $install_dir/enabledModules/doc
ln -s /usr/share/icingaweb2/modules/monitoring $install_dir/enabledModules/monitoring

chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.yml" --destination="/etc/icingadb/config.yml"
chmod 640 "/etc/icingadb/config.yml"
chown "icingadb:root" "/etc/icingadb/config.yml"

ynh_config_add --template="api-users.conf" --destination="/etc/icinga2/conf.d/api-users.conf"
chmod 644 "/etc/icinga2/conf.d/api-users.conf"
chown "nagios:nagios" "/etc/icinga2/conf.d/api-users.conf"

ynh_config_add --template="ido-mysql.conf" --destination="/etc/icinga2/features-available/ido-mysql.conf"
chmod 644 "/etc/icinga2/features-available/ido-mysql.conf"
chown "nagios:nagios" "/etc/icinga2/features-available/ido-mysql.conf"


if [ "$testing" = false ]; then

ynh_config_add --template="authentication.ini" --destination="$install_dir/authentication.ini"
ynh_config_add --template="config.ini" --destination="$install_dir/config.ini"
ynh_config_add --template="groups.ini" --destination="$install_dir/groups.ini"
ynh_config_add --template="resources.ini" --destination="$install_dir/resources.ini"
ynh_config_add --template="roles.ini" --destination="$install_dir/roles.ini"

ynh_config_add --template="/modules/director/config.ini" --destination="$install_dir/modules/director/config.ini"

ynh_config_add --template="/modules/icingadb/commandtransports.ini" --destination="$install_dir/modules/icingadb/commandtransports.ini"
ynh_config_add --template="/modules/icingadb/config.ini" --destination="$install_dir/modules/icingadb/config.ini"
ynh_config_add --template="/modules/icingadb/redis.ini" --destination="$install_dir/modules/icingadb/redis.ini"

ynh_config_add --template="/modules/monitoring/backends.ini" --destination="$install_dir/modules/monitoring/backends.ini"
ynh_config_add --template="/modules/monitoring/commandtransports.ini" --destination="$install_dir/modules/monitoring/commandtransports.ini"
ynh_config_add --template="/modules/monitoring/config.ini" --destination="$install_dir/modules/monitoring/config.ini"

ynh_config_add --template="kickstart.ini" --destination="$install_dir/modules/director/kickstart.ini"

fi

chmod -R 2770 "$install_dir"
chown -R "www-data:icingaweb2" "$install_dir"
chown "icinga:icingaweb2" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

yunohost service add "icinga2" --description="icinga2" --needs_exposed_ports=$port

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing $app..."

icinga2 api setup

ynh_systemctl --service="icinga2" --action="restart"

ynh_mysql_db_shell <<< "CREATE DATABASE ${db_name}director DEFAULT CHARACTER SET 'utf8';"
ynh_mysql_db_shell <<< "USE ${db_name}director;"
ynh_mysql_db_shell <<< "GRANT ALL PRIVILEGES ON ${db_name}director.* TO '${db_user}'@'localhost' WITH GRANT OPTION;"
ynh_mysql_db_shell <<< "FLUSH PRIVILEGES;"
ynh_mysql_db_shell "${db_name}director" < "/usr/share/icingaweb2/modules/director/schema/mysql.sql"

ynh_mysql_db_shell <<< "CREATE DATABASE ${db_name}web2 DEFAULT CHARACTER SET 'utf8';"
ynh_mysql_db_shell <<< "USE ${db_name}web2;"
ynh_mysql_db_shell <<< "GRANT ALL PRIVILEGES ON ${db_name}web2.* TO '${db_user}'@'localhost' WITH GRANT OPTION;"
ynh_mysql_db_shell <<< "FLUSH PRIVILEGES;"
ynh_mysql_db_shell "${db_name}web2" < "/usr/share/icingaweb2/schema/mysql.schema.sql"

ynh_mysql_db_shell <<< "CREATE DATABASE ${db_name}ido DEFAULT CHARACTER SET 'utf8';"
ynh_mysql_db_shell <<< "USE ${db_name}ido;"
ynh_mysql_db_shell <<< "GRANT ALL PRIVILEGES ON ${db_name}ido.* TO '${db_user}'@'localhost' WITH GRANT OPTION;"
ynh_mysql_db_shell <<< "FLUSH PRIVILEGES;"
ynh_mysql_db_shell "${db_name}ido" < "/usr/share/icinga2-ido-mysql/schema/mysql.sql"

ynh_mysql_db_shell < "/usr/share/icingadb/schema/mysql/schema.sql"

ynh_systemctl --service="icinga2" --action="restart"

systemctl enable --now icingadb-redis
icinga2 feature enable icingadb
icinga2 feature enable ido-mysql
ynh_systemctl --service="icinga2" --action="restart"
systemctl enable --now icingadb

icinga2 node setup --master
ynh_systemctl --service="icinga2" --action="restart"

if [ "$testing" = false ]; then

icingacli director migration run
icingacli director kickstart run
ynh_setup_source --source_id="linuxfabrik" --dest_dir="$install_dir/linuxfabrik"
pushd "$install_dir/linuxfabrik"
	ynh_hide_warnings ./tools/basket-join
	icingacli director basket restore --verbose < icingaweb2-module-director-basket.json
popd 
ynh_safe_rm "$install_dir/linuxfabrik"
icingacli director config render
icingacli director config deploy

fi

addgroup --system icingaweb2;
usermod -a -G icingaweb2 www-data;

token=""

if [ "$testing" = true ]; then
	icingacli setup token create
	token=$(icingacli setup token show)
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="icinga-director" --action="restart" #--wait_until="Started icinga-director.service" --log_path="systemd"
ynh_systemctl --service="icingadb-redis" --action="restart" #--wait_until="Started icingadb-redis.service" --log_path="systemd"
ynh_systemctl --service="icingadb" --action="restart" #--wait_until="Finished config sync" --log_path="systemd"
ynh_systemctl --service="icinga2" --action="restart" #--wait_until="Started icinga2.service" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed - $token ${db_name}web2 $db_user $db_pwd"
