#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "icinga2" >/dev/null; then
    yunohost service remove "icinga2"
fi
ynh_systemctl --service="icinga-director" --action="stop"
ynh_systemctl --service="icingadb" --action="stop"
ynh_systemctl --service="icingadb-redis" --action="stop"
ynh_systemctl --service="icinga2" --action="stop"

ynh_config_remove_nginx

ynh_config_remove_phpfpm

ynh_mysql_drop_db "${db_name}director"
ynh_mysql_drop_db "${db_name}web2"

ynh_safe_rm "/etc/icinga2"
ynh_safe_rm "/etc/icingadb"
ynh_safe_rm "/etc/icingadb-redis"
ynh_safe_rm "/etc/icingaweb2"
ynh_safe_rm "/etc/nagios-plugins"
ynh_safe_rm "/run/icinga2"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
