#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="icinga2" --action="stop"
ynh_systemctl --service="icingadb" --action="stop"
ynh_systemctl --service="icingadb-redis" --action="stop"
ynh_systemctl --service="icinga-director" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

chmod -R 2770 "$install_dir"
chown -R "www-data:icingaweb2" "$install_dir"
chown "icinga:icingaweb2" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

yunohost service add "icinga2" --description="icinga2"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="icinga-director" --action="restart"
ynh_systemctl --service="icingadb-redis" --action="restart"
ynh_systemctl --service="icingadb" --action="restart"
ynh_systemctl --service="icinga2" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
